export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"

export const GET_USER_LIST = "GET_USER_LIST"
export const GET_USER_LIST_BEGIN = "GET_USER_LIST_BEGIN"
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS"
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL"

export const REMOVE_MESSAGE = "REMOVE_MESSAGE"