export const ADD_TODO = "ADD_TODO"
export const ADD_TODO_BEGIN = "ADD_TODO_BEGIN"
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
export const ADD_TODO_FAIL = "ADD_TODO_FAIL"


export const GET_TODO = "GET_TODO"
export const GET_TODO_BEGIN = "GET_TODO_BEGIN"
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS"
export const GET_TODO_FAIL = "GET_TODO_FAIL"

export const GET_TODO_BY_ID = "GET_TODO_BY_ID"
export const GET_TODO_BY_ID_BEGIN = "GET_TODO_BY_ID_BEGIN"
export const GET_TODO_BY_ID_SUCCESS = "GET_TODO_BY_ID_SUCCESS"
export const GET_TODO_BY_ID_FAIL = "GET_TODO_BY_ID_FAIL"

export const UPDATE_TODO = "UPDATE_TODO"
export const UPDATE_TODO_BEGIN = "UPDATE_TODO_BEGIN"
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS"
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL"

export const DELETE_TODO = "DELETE_TODO"
export const DELETE_TODO_BEGIN = "DELETE_TODO_BEGIN"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL"
